export const BOSS_DATABASE = [
  { isim: "Margit, the Fell Omen", oyun: "elden-ring" },
  { isim: "Godrick the Grafted", oyun: "elden-ring" },
  { isim: "Red Wolf of Radagon", oyun: "elden-ring" },
  { isim: "Rennala, Queen of the Full Moon", oyun: "elden-ring" },
  { isim: "Starscourge Radahn", oyun: "elden-ring" },
  { isim: "Rykard, Lord of Blasphemy", oyun: "elden-ring" },
  { isim: "Morgott, the Omen King", oyun: "elden-ring" },
  { isim: "Fire Giant", oyun: "elden-ring" },
  { isim: "Godskin Duo", oyun: "elden-ring" },
  { isim: "Maliketh, the Black Blade", oyun: "elden-ring" },
  { isim: "Godfrey, First Elden Lord", oyun: "elden-ring" },
  { isim: "Hoarah Loux, Warrior", oyun: "elden-ring" },
  { isim: "Radagon of the Golden Order", oyun: "elden-ring" },
  { isim: "Elden Beast", oyun: "elden-ring" },
  { isim: "Malenia, Blade of Miquella", oyun: "elden-ring" },
  { isim: "Mohg, Lord of Blood", oyun: "elden-ring" },
  { isim: "Dragonlord Placidusax", oyun: "elden-ring" },
  { isim: "Lichdragon Fortissax", oyun: "elden-ring" },
  { isim: "Astel, Naturalborn of the Void", oyun: "elden-ring" },
  { isim: "Mimic Tear", oyun: "elden-ring" },
  { isim: "Valiant Gargoyle", oyun: "elden-ring" },
  { isim: "Magma Wyrm Makar", oyun: "elden-ring" },
  { isim: "Commander Niall", oyun: "elden-ring" },
  { isim: "Loretta, Knight of the Haligtree", oyun: "elden-ring" },
  { isim: "Royal Knight Loretta", oyun: "elden-ring" },
  { isim: "Elemer of the Briar", oyun: "elden-ring" },
  { isim: "Crucible Knight Ordovis", oyun: "elden-ring" },
  { isim: "Godskin Apostle", oyun: "elden-ring" },
  { isim: "Godskin Noble", oyun: "elden-ring" },
  { isim: "Leonine Misbegotten", oyun: "elden-ring" },
  { isim: "Ancestor Spirit", oyun: "elden-ring" },
  { isim: "Regal Ancestor Spirit", oyun: "elden-ring" },
  { isim: "Tree Sentinel", oyun: "elden-ring" },
  { isim: "Flying Dragon Agheel", oyun: "elden-ring" },
  { isim: "Glintstone Dragon Smarag", oyun: "elden-ring" },
  { isim: "Borealis the Freezing Fog", oyun: "elden-ring" },
  { isim: "Decaying Ekzykes", oyun: "elden-ring" },
  { isim: "Glintstone Dragon Adula", oyun: "elden-ring" },
  { isim: "Ancient Dragon Lansseax", oyun: "elden-ring" },
  { isim: "Alecto, Black Knife Ringleader", oyun: "elden-ring" },
  { isim: "Esgar, Priest of Blood", oyun: "elden-ring" },
  { isim: "Fell Twins", oyun: "elden-ring" },
  { isim: "Divine Beast Dancing Lion", oyun: "elden-ring" },
  { isim: "Rellana, Twin Moon Knight", oyun: "elden-ring" },
  { isim: "Messmer the Impaler", oyun: "elden-ring" },
  { isim: "Commander Gaius", oyun: "elden-ring" },
  { isim: "Romina, Saint of the Bud", oyun: "elden-ring" },
  { isim: "Scadutree Avatar", oyun: "elden-ring" },
  { isim: "Midra, Lord of Frenzied Flame", oyun: "elden-ring" },
  { isim: "Bayle the Dread", oyun: "elden-ring" },
  { isim: "Putrescent Knight", oyun: "elden-ring" },
  { isim: "Metyr, Mother of Fingers", oyun: "elden-ring" },
  { isim: "Promised Consort Radahn", oyun: "elden-ring" },
  { isim: "Needle Knight Leda", oyun: "elden-ring" },
  { isim: "Count Ymir, Mother of Fingers", oyun: "elden-ring" },

  { isim: "Gyoubu Masataka Oniwa", oyun: "sekiro" },
  { isim: "Lady Butterfly", oyun: "sekiro" },
  { isim: "Genichiro Ashina", oyun: "sekiro" },
  { isim: "Folding Screen Monkeys", oyun: "sekiro" },
  { isim: "Guardian Ape", oyun: "sekiro" },
  { isim: "Headless Ape", oyun: "sekiro" },
  { isim: "Corrupted Monk (Illusion)", oyun: "sekiro" },
  { isim: "Corrupted Monk", oyun: "sekiro" },
  { isim: "Divine Dragon", oyun: "sekiro" },
  { isim: "Owl", oyun: "sekiro" },
  { isim: "Owl (Father)", oyun: "sekiro" },
  { isim: "Emma, the Gentle Blade", oyun: "sekiro" },
  { isim: "Isshin Ashina", oyun: "sekiro" },
  { isim: "Isshin, the Sword Saint", oyun: "sekiro" },
  { isim: "Demon of Hatred", oyun: "sekiro" },
  { isim: "Genichiro, Way of Tomoe", oyun: "sekiro" },
  { isim: "O'Rin of the Water", oyun: "sekiro" },
  { isim: "Armored Warrior", oyun: "sekiro" },
  { isim: "Juzou the Drunkard", oyun: "sekiro" },
  { isim: "Tokujiro the Glutton", oyun: "sekiro" },
  { isim: "Snake Eyes Shirafuji", oyun: "sekiro" },
  { isim: "Snake Eyes Shirahagi", oyun: "sekiro" },
  { isim: "Lone Shadow Masanaga", oyun: "sekiro" },
  { isim: "Lone Shadow Vilehand", oyun: "sekiro" },
  { isim: "Seven Ashina Spears - Shume Masaji Oniwa", oyun: "sekiro" },

  { isim: "Cleric Beast", oyun: "bloodborne" },
  { isim: "Father Gascoigne", oyun: "bloodborne" },
  { isim: "Blood-Starved Beast", oyun: "bloodborne" },
  { isim: "Vicar Amelia", oyun: "bloodborne" },
  { isim: "The Witch of Hemwick", oyun: "bloodborne" },
  { isim: "Shadow of Yharnam", oyun: "bloodborne" },
  { isim: "Rom, the Vacuous Spider", oyun: "bloodborne" },
  { isim: "The One Reborn", oyun: "bloodborne" },
  { isim: "Micolash, Host of the Nightmare", oyun: "bloodborne" },
  { isim: "Mergo's Wet Nurse", oyun: "bloodborne" },
  { isim: "Celestial Emissary", oyun: "bloodborne" },
  { isim: "Ebrietas, Daughter of the Cosmos", oyun: "bloodborne" },
  { isim: "Gehrman, the First Hunter", oyun: "bloodborne" },
  { isim: "Moon Presence", oyun: "bloodborne" },
  { isim: "Darkbeast Paarl", oyun: "bloodborne" },
  { isim: "Amygdala", oyun: "bloodborne" },
  { isim: "Alfred, Hunter of Vilebloods", oyun: "bloodborne" },
  { isim: "Ludwig, the Accursed", oyun: "bloodborne" },
  { isim: "Living Failures", oyun: "bloodborne" },
  { isim: "Lady Maria of the Astral Clocktower", oyun: "bloodborne" },
  { isim: "Laurence, the First Vicar", oyun: "bloodborne" },
  { isim: "Orphan of Kos", oyun: "bloodborne" },
  { isim: "Logarius", oyun: "bloodborne" },

  { isim: "Parade Master", oyun: "lies-of-p" },
  { isim: "Scrapped Watchman", oyun: "lies-of-p" },
  { isim: "Mad Donkey", oyun: "lies-of-p" },
  { isim: "Fallen Archbishop Andreus", oyun: "lies-of-p" },
  { isim: "King's Flame, Fuoco", oyun: "lies-of-p" },
  { isim: "Black Rabbit Brotherhood", oyun: "lies-of-p" },
  { isim: "Puppet-Devouring Green Monster of the Swamp", oyun: "lies-of-p" },
  { isim: "Champion Victor", oyun: "lies-of-p" },
  { isim: "Door Guardian", oyun: "lies-of-p" },
  { isim: "Corrupted Parade Master", oyun: "lies-of-p" },
  { isim: "Laxasia The Complete", oyun: "lies-of-p" },
  { isim: "Simon Manus, Arm of God", oyun: "lies-of-p" },
  { isim: "Simon Manus, Awakened God", oyun: "lies-of-p" },
  { isim: "Nameless Puppet", oyun: "lies-of-p" },
  { isim: "Rookie Explorer Hugo", oyun: "lies-of-p" },
  { isim: "White Lady Lorenzini Isabelle", oyun: "lies-of-p" },
  { isim: "Elder of the Covenant", oyun: "lies-of-p" },
];
